# Generated by Django 2.1.3 on 2019-01-03 19:30

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('partysize', models.IntegerField()),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('status', models.BooleanField(choices=[(True, 'Waiting'), (False, 'Seated')], default=True)),
                ('table_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('highlighted', models.TextField()),
            ],
        ),
    ]
